services:
  app:
    # build: ../../.
    image: taufikp/monitoring-psre:latest
    container_name: monitoring-app
    # command: fastapi dev /app/src/app.py
    ports:
      - 80:80
      # - 5678:5678
    volumes:
      - /home/taufik/project-shared/api-monitoring-psre-v2/src:/app/src
      - /home/taufik/project-shared/api-monitoring-psre-v2/data:/app/data
      - /home/taufik/project-shared/api-monitoring-psre-v2/input:/app/input
      - /home/taufik/project-shared/api-monitoring-psre-v2/temp:/app/tmp
      - /home/taufik/project-shared/api-monitoring-psre-v2/logs:/app/logs:rw
    environment:
      NODE_NAME: PROD
      TZ: "Asia/Jakarta"
      INFLUX_BUCKET: monitoring
      INFLUX_URL: http://influxdb:8086
      INFLUX_ORG: org
      INFLUX_TOKEN: s3cr3ttok3n
      TIME_INTERVAL: 180
      TELEGRAM_BOT_TOKEN: 917180406:AAGDpIQdIDQ6IArbaifIJaUgYX-6_sE50qo
      TELEGRAM_CHAT_ID: -1002150723538 
      SEND_NOTIF: 0
    depends_on:
      - mongo
      - influxdb
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    environment:
      TZ: "Asia/Jakarta"
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234qweR

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdata:/var/lib/influxdb2
      - influxconfig:/etc/influxdb2
    environment:
      TZ: "Asia/Jakarta"
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: 1234qweR
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: monitoring
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: s3cr3ttok3n

  celery_worker1:
    container_name: celery_worker1
    restart: always
    build: ../../app/.
    command: celery -A src.celery worker --concurrency=3 --pool=prefork --loglevel=debug
    volumes:
      - /home/taufik/project-shared/api-monitoring-psre-v2/app/src:/app/src
    environment:
      TZ: "Asia/Jakarta"
      CELERY_TIMEZONE: "Asia/Jakarta"
      CELERY_ENABLE_UTC: False
      TELEGRAM_BOT_TOKEN: 917180406:AAGDpIQdIDQ6IArbaifIJaUgYX-6_sE50qo
      TELEGRAM_CHAT_ID: -1002150723538 
      SEND_NOTIF: 1
    depends_on:
      - redis
      - influxdb
      - app

  celery_worker2:
    container_name: celery_worker2
    restart: always
    build: ../../app/.
    command: celery -A src.celery worker --concurrency=3 --pool=prefork --loglevel=debug
    volumes:
      - /home/taufik/project-shared/api-monitoring-psre-v2/app/src:/app/src
    environment:
      TZ: "Asia/Jakarta"
      CELERY_TIMEZONE: "Asia/Jakarta"
      CELERY_ENABLE_UTC: False
      TELEGRAM_BOT_TOKEN: 917180406:AAGDpIQdIDQ6IArbaifIJaUgYX-6_sE50qo
      TELEGRAM_CHAT_ID: -1002150723538 
      SEND_NOTIF: 1
    depends_on:
      - redis
      - influxdb
      - app

  flower:
    container_name: flower
    restart: always
    build: ../../app/.
    command: celery -A src.celery flower --broker=redis://redis:6379/0 --port=5555
    environment:
      TZ: "Asia/Jakarta"
    ports:
      - 5556:5555
    depends_on:
      - app
      - redis
      - celery_worker1
      - celery_worker2


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      TZ: "Asia/Jakarta"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234qweR
      ME_CONFIG_MONGODB_URL: mongodb://root:1234qweR@mongo:27017/

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
      - app
    volumes:
      - grafana:/var/lib/grafana

volumes:
  mongodb:
  mongoconfig:
  grafana:
  influxdata:
  influxconfig:
